C++ LRU Cache Template: lru_cache.cpp File Reference
lru_cache.cpp File Reference
Typedefs
typedef LRUCache< std::string,
std::string > unit_lru_type
LRUCache type for use in the unit tests.
typedef LRUCache< int, int > unit_lru_type2
LRUCache POD type for use in the unit tests.
typedef LRUCache< int,
test_big_data > unit_lru_type3
LRUCache with large data for use in the unit tests.
Functions
std::string dump (unit_lru_type *L)
Dumps the cache for debugging.
UNIT_TEST_DEFINES DEFINE_TEST (lru_cache_1cycle)
DEFINE_TEST (lru_cache_stress)
DEFINE_TEST (lru_cache_scope_check)
DEFINE_TEST (lru_cache_threads)
Variables
unit_lru_type3 * L3
Scoping test object.
Detailed Description
Template cache with an LRU removal policy (unit tests)
Author:
Patrick Audley
Definition in file lru_cache.cpp.
Function Documentation
UNIT_TEST_DEFINES DEFINE_TEST (lru_cache_1cycle)
Test:
Basic creation and desctruction test
Definition at line 50 of file lru_cache.cpp.
References LRUCache< Key, Data, Sizefn >::clear(), dump(), LRUCache< Key, Data, Sizefn >::exists(), LRUCache< Key, Data, Sizefn >::fetch(), LRUCache< Key, Data, Sizefn >::insert(), LRUCache< Key, Data, Sizefn >::max_size(), LRUCache< Key, Data, Sizefn >::remove(), LRUCache< Key, Data, Sizefn >::size(), LRUCache< Key, Data, Sizefn >::touch(), unit_assert, and unit_pass.
{
        const std::string unit_data_1cycle_a("foo:4\n");
        const std::string unit_data_1cycle_b("bar:flower\nfoo:4\n");
        const std::string unit_data_1cycle_c("foo:4\nbar:flower\n");
        const std::string unit_data_1cycle_d("foo:moose\nbaz:Stalin\nbar:flower\n");
        const std::string unit_data_1cycle_e("foo:moose\nbar:flower\n");
        const std::string unit_data_1cycle_f("quz:xyzzy\nbaz:monkey\nfoo:moose\n");
        const std::string unit_data_1cycle_g("coat:mouse\npants:cat\nsocks:bear\n");
        unit_lru_type *L = new unit_lru_type(3);
        unit_assert( "size==0", (L->size() == 0) );
        unit_assert( "maxsize==3", (L->max_size() == 3) );
        // Checking a bogus key shouldn't alter the cache.
        L->exists( "foo" );
        unit_assert( "exists() doesn't increase size", (L->size() == 0) );
        // Check insert() and exists()
        L->insert( "foo", "4" );
        unit_assert( "size==1 after insert(foo,4)", (L->size() == 1) );
        unit_assert( "check exists(foo)", L->exists( "foo" ) );
        unit_assert( "contents check a)", unit_data_1cycle_a.compare( dump( L ) ) == 0 );
        // Check second insert and ordering
        L->insert( "bar", "flower" );
        unit_assert( "size==2 after insert(bar,flower)", (L->size() == 2) );
        unit_assert( "contents check b)", unit_data_1cycle_b.compare( dump( L ) ) == 0 );
        // Check touching
        L->touch( "foo" );
        unit_assert( "contents check c)", unit_data_1cycle_c.compare( dump( L ) ) == 0 );
        // Insert of an existing element should result in only a touch
        L->insert( "bar", "flower" );
        unit_assert( "verify insert touches", unit_data_1cycle_b.compare( dump( L ) ) == 0 );
        // Verify that fetch works
        unit_assert( "verify fetch(bar)", ( std::string("flower").compare( L->fetch("bar") ) == 0 ) );
        // Insert of an existing element with new data should replace and touch
        L->insert( "baz", "Stalin" );
        L->insert( "foo", "moose" );
        unit_assert( "verify insert replaces", unit_data_1cycle_d.compare( dump( L ) ) == 0 );
        // Test removal of an existing member.
        L->remove( "baz" );
        unit_assert( "verify remove works", unit_data_1cycle_e.compare( dump( L ) ) == 0 );
        // Test LRU removal as we add more members than max_size()
        L->insert( "baz", "monkey" );
        L->insert( "quz", "xyzzy" );
        unit_assert( "verify LRU semantics", unit_data_1cycle_f.compare( dump( L ) ) == 0 );
        // Stress test the implementation a little..
        const char *names[10] = { "moose", "dog", "bear", "cat", "mouse", "hat", "mittens", "socks", "pants", "coat" };
        for( int i = 0; i < 50; i++ ) {
                L->insert( names[ i % 10 ], names[ i % 9 ] );
        }
        unit_assert( "stress test a little", unit_data_1cycle_g.compare( dump( L ) ) == 0 );
        // Setup a little for the third test which verifies that scoped references inserted into the cache don't disappear.
        L3 = new unit_lru_type3(2);
        for( int i = 0; i < 10; i++ ) {
                test_big_data B;
                snprintf( B.buffer, 1000, "%d\n", i );
                L3->insert( i, B );
        }
        // Check that clear fully clears.
        //   Bug discovered by:  月迷津渡 gdcex@qq.com
        unit_assert( "very size before clear.", (L->size() > 0) );
        L->clear();
        unit_assert( "very size after clear.", (L->size() == 0) );
        unit_pass();
}
DEFINE_TEST (lru_cache_stress)
Test:
Insert lots of objects and benchmark the rate.
Definition at line 129 of file lru_cache.cpp.
References cputime(), LRUCache< Key, Data, Sizefn >::insert(), print_cputime(), and unit_pass.
{
        // Stress test the implementation a little more using no objects
        unit_lru_type2 *L2 = new unit_lru_type2(5);
        double t0 = cputime();
        for( int i = 0; i < TRANSACTIONS; i++ ) {
                L2->insert( i, i-1 );
        }
        double t1 = cputime();
        delete L2;
        print_cputime( "(int,int) inserts", t1-t0, TRANSACTIONS );
        unit_pass();
}
DEFINE_TEST (lru_cache_scope_check)
Test:
Check that objects inserted in a different scope are still there.
Definition at line 143 of file lru_cache.cpp.
References LRUCache< Key, Data, Sizefn >::fetch_ptr(), L3, unit_assert, and unit_pass.
{
        test_big_data* B = L3->fetch_ptr( 9 );
        unit_assert( "scope check element L3[1]", ( strncmp( B->buffer, "9\n", 1000 ) == 0 ) );
        B = L3->fetch_ptr( 8 );
        unit_assert( "scope check element L3[2]", ( strncmp( B->buffer, "8\n", 1000 ) == 0 ) );
        delete L3;
        unit_pass();
}
DEFINE_TEST (lru_cache_threads)
Test:
Check for badness with multithreaded access, this is more of a stress test than an empirical test.
Definition at line 170 of file lru_cache.cpp.
References cputime(), print_cputime(), and unit_pass.
{
        L4 = new unit_lru_type2( 20 );
        boost::thread_group thrds;
        double t0 = cputime();
        for (int i=0; i < THREAD_COUNT; ++i)
                thrds.create_thread(&insert_junk);
        thrds.join_all();
        double t1 = cputime();
        print_cputime( "(int,int) multithreaded inserts", t1-t0, THREAD_TRANS*THREAD_COUNT*4 );
        delete L4;
        unit_pass();
}