C++ LRU Cache Template: unit_test.h File Reference
unit_test.h File Reference
Macros
#define UNIT_TEST_DEFINES
Start of inline Unit Test definitions Use this to start the list of unit tests. This should be followed by one or more DEFINE_TEST entries.
#define DEFINE_TEST(test_name) bool unit_test_##test_name (void)
Start a new test definition.
#define ADD_TEST(test_name) add_test(&unit_test_##test_name);
Adds a defined test to test run.
#define UNIT_TEST_RUN(suite)
Start a Unit test run section.
#define unit_assert(msg, cond)
Use within a Unit Test to verify a condition.
#define unit_pass() return true;
Use to end a unit test in success.
#define unit_fail() return false;
Use to end a unit test in failure.
#define UNIT_TEST_END
Finish a Unit Test run section.
Typedefs
typedef bool(* test_func)(void)
typedef for unittest functions
typedef std::vector< test_func > test_vector
typedef for vectors of unittest functions
Functions
double cputime (void)
Gets the current CPU time with microsecond accuracy.
double transactions_per_second (double run_time, unsigned long transactions)
Calculates the transactions rate.
void print_cputime (const char *msg, double run_time, unsigned long transactions=0)
Prints to stdout the results of timing an event.
Detailed Description
Unit Testing framework for C++
Author:
Patrick Audley
Date:
December 2004
See full documentation for this framework in Unit Testing Framework
Definition in file unit_test.h.
Macro Definition Documentation
#define DEFINE_TEST (test_name) bool unit_test_##test_name (void)
Start a new test definition.
Parameters:
test_name Name of the test - must be unique in this unit test suite.
Definition at line 184 of file unit_test.h.
#define ADD_TEST (test_name) add_test(&unit_test_##test_name);
Adds a defined test to test run.
Parameters:
test_name Test name of a previously defined test to add the the current suite.
See also:
DEFINE_TEST UNIT_TEST_RUN This should be called after UNIT_TEST_RUN for each defined test.
Definition at line 191 of file unit_test.h.
#define UNIT_TEST_RUN (suite)
Value:
int main(void) { \
  bool result = true; \
  std::cout << "---[ " << suite << " ]--- " << std::endl;
Start a Unit test run section.
Parameters:
suite Name for this test suite.
Note:
Must be terminated with an UNIT_TEST_END statement.
Definition at line 197 of file unit_test.h.
#define unit_assert (msg, cond)
Value:
std::cout << "  " << msg << ": " << std::flush; \
  if( !cond ) { std::cout << "FAILED" << std::endl; return false; } \
  std::cout << "PASSED" << std::endl;
Use within a Unit Test to verify a condition.
Warning:
Terminates test on failure.
Definition at line 205 of file unit_test.h.
Referenced by DEFINE_TEST().
#define unit_pass () return true;
Use to end a unit test in success.
Note:
Either unit_pass or unit_fail should end every test.
Definition at line 213 of file unit_test.h.
Referenced by DEFINE_TEST().
#define unit_fail () return false;
Use to end a unit test in failure.
Note:
Either unit_pass or unit_fail should end every test.
Definition at line 218 of file unit_test.h.
Function Documentation
double cputime (void) inline
Gets the current CPU time with microsecond accuracy.
Returns:
microseconds since UNIX epoch
Definition at line 139 of file unit_test.h.
Referenced by DEFINE_TEST().
{
  getrusage( RUSAGE_SELF, &ruse );
        return ( ruse.ru_utime.tv_sec + ruse.ru_stime.tv_sec + 1e-6 * (ruse.ru_utime.tv_usec + ruse.ru_stime.tv_usec ) );
}
double transactions_per_second (double run_time, unsigned long transactions) inline
Calculates the transactions rate.
Parameters:
run_time microsecond resolution run time
transactions number of transactions handled in run_time seconds This is useful if you want to guarantee minimun transactional throughputs in unit tests.
Warning:
This code is obviously very test platform dependent.
Definition at line 149 of file unit_test.h.
Referenced by print_cputime().
{
        return (double)transactions / run_time;
}
void print_cputime (const char * msg, double run_time, unsigned long transactions = 0) inline
Prints to stdout the results of timing an event.
Parameters:
msg to print with the numbers
run_time microsecond resolution run time
transactions number of transactions handled in run_time seconds, if 0 then transactional output is suppressed
Warning:
This code is obviously very test platform dependent.
Definition at line 158 of file unit_test.h.
References transactions_per_second().
Referenced by DEFINE_TEST().
{
        printf("  -> %s:  %7.3f seconds CPU time", msg, run_time );
        if( transactions != 0 )
                printf( "  (%7.3f transactions/second)", transactions_per_second( run_time, transactions ) );
        printf( "\n" );
}